In [1]:
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor

In [2]:
# Download training data from open datasets.
training_data = datasets.FashionMNIST(
    root="data",
    train=True,
    download=True,
    transform=ToTensor(),
)

# Download test data from open datasets.
test_data = datasets.FashionMNIST(
    root="data",
    train=False,
    download=True,
    transform=ToTensor(),
)

100%|█████████████████████████| 26421880/26421880 [00:00<00:00, 38657718.84it/s]


Extracting data/FashionMNIST/raw/train-images-idx3-ubyte.gz to data/FashionMNIST/raw



100%|█████████████████████████████████| 29515/29515 [00:00<00:00, 664998.99it/s]


Extracting data/FashionMNIST/raw/train-labels-idx1-ubyte.gz to data/FashionMNIST/raw



100%|███████████████████████████| 4422102/4422102 [00:00<00:00, 12007750.75it/s]


Extracting data/FashionMNIST/raw/t10k-images-idx3-ubyte.gz to data/FashionMNIST/raw



100%|█████████████████████████████████| 5148/5148 [00:00<00:00, 10426014.96it/s]

Extracting data/FashionMNIST/raw/t10k-labels-idx1-ubyte.gz to data/FashionMNIST/raw



In [3]:
batch_size = 64

# Create data loaders.
train_dataloader = DataLoader(training_data, batch_size=batch_size)
test_dataloader = DataLoader(test_data, batch_size=batch_size)

for X, y in test_dataloader:
    print(f"Shape of X [N, C, H, W]: {X.shape}")
    print(f"Shape of y: {y.shape} {y.dtype}")
    break

Shape of X [N, C, H, W]: torch.Size([64, 1, 28, 28])
Shape of y: torch.Size([64]) torch.int64


In [4]:
device = (
    "cuda:1"
    if torch.cuda.is_available()
    else "mps"
    if torch.backends.mps.is_available()
    else "cpu"
)
print(f"Using {device} device")

Using cuda:1 device


In [5]:
from torchvision.models import resnet50

In [6]:
model = resnet50(weights="IMAGENET1K_V1").to(device)

In [7]:
model

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): Bottleneck(
      (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (downsample): Sequential(
        (0): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 

In [8]:
bn = nn.BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)

In [9]:
bn.state_dict()

OrderedDict([('weight',
              tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
                      1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
                      1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
                      1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])),
             ('bias',
              tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
                      0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
                      0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])),
             ('running_mean',
              tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
                      0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
                

In [10]:
list(bn.buffers())

[tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 tensor(0)]

In [11]:
list(bn.buffers())[0] is bn.running_mean

True

In [12]:
list(model.buffers())

[tensor([ 2.4589e-04, -6.6723e-02,  8.1560e-03, -1.1569e-02,  9.1918e-04,
         -3.9417e-03,  6.8244e-05, -1.0278e-04,  6.2920e-05,  1.0156e-02,
         -1.3827e-03,  8.5514e-03, -9.6786e-04, -5.0542e-09, -1.3922e-03,
          9.7684e-04, -4.2287e-03, -4.3058e-04,  8.8580e-04, -5.7929e-02,
          3.4196e-03, -6.9578e-04, -2.2842e-03,  4.3616e-02,  2.6490e-03,
          4.7517e-03, -1.1206e-03, -3.1145e-04,  2.6560e-03,  5.6712e-02,
         -6.8490e-04, -5.3309e-03, -1.4519e-02, -5.2398e-04, -3.5607e-02,
          8.8422e-02,  1.7903e-03,  4.4882e-03,  1.6055e-03, -3.0522e-04,
          2.9796e-03, -1.2307e-03,  7.8966e-03,  5.9528e-03,  9.8027e-03,
         -1.4366e-03,  3.5911e-04, -9.7358e-04, -9.1738e-03,  7.6298e-05,
         -3.3611e-04, -4.8319e-05,  3.6836e-03, -2.1531e-03, -2.1549e-04,
         -8.7561e-07,  3.4184e-02, -3.5004e-03,  1.1910e-02, -1.0551e-03,
          5.2965e-04,  6.0597e-04, -8.4048e-03, -1.6792e-03], device='cuda:1'),
 tensor([1.0956e+00, 3.8935e+00,

In [13]:
# https://discuss.pytorch.org/t/should-i-use-model-eval-when-i-freeze-batchnorm-layers-to-finetune/39495/4

normalization_layers = [
    nn.BatchNorm1d, nn.BatchNorm2d, nn.BatchNorm3d, nn.LazyBatchNorm1d, nn.LazyBatchNorm2d, nn.LazyBatchNorm3d,
    nn.LazyBatchNorm3d, nn.GroupNorm, nn.SyncBatchNorm, nn.InstanceNorm1d, nn.InstanceNorm2d, nn.InstanceNorm3d,
    nn.LazyInstanceNorm1d, nn.LazyInstanceNorm2d, nn.LazyInstanceNorm3d, nn.LayerNorm, nn.LocalResponseNorm
]

def is_norm_layer(layer):
    """
    Check if a layer is a normalization layer.

    Args:
        layer (torch.nn.Module): A layer from the model.

    Returns:
        bool: True if the layer is a normalization layer, False otherwise.
    """
    for norm_layer in normalization_layers:
        if isinstance(layer, norm_layer):
            return True
    return False

def set_norm_eval_and_freeze(module):
    """
    Recursively sets normalization layers to evaluation mode and freezes their parameters.

    Args:
        module (torch.nn.Module): A module from the model.
    """
    for layer in module.children():
        if is_norm_layer(layer):
            # Set the layer to evaluation mode
            layer.eval()
            # Freeze the layer parameters
            for param in layer.parameters():
                param.requires_grad = False
                
        # Recursively apply to child modules
        set_norm_eval_and_freeze(layer)

In [14]:
# The trainable parameters of the `model`, by reference
# Lies in `device` (same as each `param`)
trainable_parameters = [param for param in model.parameters() if param.requires_grad]

In [10]:
# Lies in `device` (same as each `param`)
round_start_trainable_parameters = [param.detach().clone() for param in trainable_parameters]

In [11]:
# Lies in `device` (same as each `param`)
aggregated_trainable_parameters = [torch.zeros_like(param) for param in trainable_parameters]

In [38]:

with torch.no_grad():
    trainable_parameters[0].data.copy_(1)

In [26]:
trainable_parameters[0].data is trainable_parameters[0].data

False

In [34]:
trainable_parameters[0].grad = torch.ones_like(trainable_parameters[0])

In [42]:
model.weights

AttributeError: 'ResNet' object has no attribute 'weights'

In [12]:
# ----- LOOP

In [13]:
@torch.no_grad
def zero_parameters(parameters):
    """
    Sets all parameters in the given iterable to zero.

    This function operates in-place and modifies the parameters directly.
    The @torch.no_grad() decorator ensures that this operation is not tracked 
    by autograd, preventing unnecessary computation and memory usage.

    Args:
        parameters (iterable): An iterable of parameters to be zeroed.
    """
    for param in parameters:
        param.zero_()

In [14]:
zero_parameters(aggregated_trainable_parameters)

In [17]:
@torch.no_grad
def copy_parameters(from_parameters, to_parameters):
    """
    Copies the values from one set of parameters to another.

    This function operates in-place and modifies the `to_parameters` directly.
    The @torch.no_grad() decorator ensures that this operation is not tracked 
    by autograd, preventing unnecessary computation and memory usage.

    Args:
        from_parameters (iterable): An iterable of source parameters to copy from.
        to_parameters (iterable): An iterable of destination parameters to copy to.
    """
    for from_param, to_param in zip(from_parameters, to_parameters):
        to_param.copy_(from_param)

In [18]:
copy_parameters(
    from_parameters=trainable_parameters, 
    to_parameters=round_start_trainable_parameters
)

In [ ]:
# -------------- TRAIN ONE CLIENT

In [91]:
# incorporate the client's learnt weights
with torch.no_grad():
    for param, aggr_param in zip(trainable_parameters, aggregated_trainable_parameters):
        # TODO: n - current client's number of samples
        n = 1
        aggr_param.add_(n * param)

In [ ]:
# divide with the number of total samples seen in this round (all clients)
# TODO: N?
N = 1
for param in aggregated_trainable_parameters:
    param.div_(N)

In [ ]:
# -------------- set 

In [51]:
copy_parameters(
    from_parameters=aggregated_trainable_parameters, 
    to_parameters=trainable_parameters
)

In [19]:
loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=1e-3)

In [20]:
optimizer

SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    fused: None
    lr: 0.001
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)

In [21]:
for i, (X, y) in enumerate(train_dataloader):
    X, y = X.to(device), y.to(device)
    
    pred = model(X)
    loss = loss_fn(pred, y)
    
    loss.backward()
    optimizer.step()
    optimizer.zero_grad()
    
    if i % 100 == 0:
        print(f"step: {i} loss: {loss.item()}")

step: 0 loss: 2.296342611312866
step: 100 loss: 2.285388708114624
step: 200 loss: 2.2608916759490967
step: 300 loss: 2.2562592029571533
step: 400 loss: 2.2390575408935547
step: 500 loss: 2.207130193710327
step: 600 loss: 2.2198007106781006
step: 700 loss: 2.1795337200164795
step: 800 loss: 2.17801833152771
step: 900 loss: 2.137843370437622


In [22]:
torch.cuda.device_count()

2

In [24]:
for param in model.parameters():
    print(param)

Parameter containing:
tensor([[ 4.3669e-03,  2.1338e-02, -9.4513e-03,  ..., -1.7497e-02,
          2.3945e-02, -1.9731e-02],
        [-6.5312e-03, -1.6197e-02,  1.0933e-02,  ..., -1.6745e-02,
         -1.7878e-02,  1.0006e-04],
        [ 4.9304e-05, -2.0549e-02,  1.7578e-02,  ...,  1.9917e-02,
          3.2548e-02, -1.1593e-02],
        ...,
        [ 5.0174e-03,  1.0568e-02,  3.7502e-03,  ...,  3.5528e-02,
          2.3718e-02, -3.0400e-02],
        [-2.0251e-03, -1.4187e-02,  1.8873e-02,  ..., -1.8869e-02,
          2.0945e-02,  3.1183e-02],
        [ 2.1701e-02,  9.8920e-04, -1.3297e-02,  ...,  2.5257e-02,
          1.2244e-02, -1.0713e-02]], device='cuda:1', requires_grad=True)
Parameter containing:
tensor([ 2.5470e-03,  1.9033e-02, -7.9378e-03,  1.3671e-02,  1.5233e-02,
        -2.1608e-02, -2.0272e-02, -6.7551e-03, -7.0963e-04, -2.9148e-02,
        -1.8611e-02,  1.8206e-02, -3.3048e-02,  3.4167e-02, -2.7647e-02,
        -1.1790e-03, -3.4330e-02, -1.4383e-02, -1.3384e-02, -1.8263e