In [1]:
d1 = {}
d2 = {'mike': 2}
d3 = {'s': (1,2)}

In [2]:
{**d1, **d2, **d3}

{'mike': 2, 's': (1, 2)}

In [3]:
import ast

In [7]:
type(ast.literal_eval('0.99'))

float

In [ ]:
python -m fdaopt.miscellaneous.create_hyperparameters --checkpoint roberta-base --ds_path glue --ds_name mrpc --num_labels 2 --num_clients 100 --clients_per_round 10 --alpha 1. --batch_size 8 --local_epochs 1 --total_rounds 1000 --server_opt_name Adam --client_opt_name 'SGD' --server_opt_args lr=0.001 betas='(0.9, 0.99)'

In [9]:
x1 = {"checkpoint": "roberta-base", "ds_path": "glue", "ds_name": "mrpc", "num_labels": 2, "num_clients": 100, "clients_per_round": 10, "alpha": 1.0, "batch_size": 8, "local_epochs": 1, "total_rounds": 1000, "server_opt_name": "Adam", "client_opt_name": "SGD", "server_opt_lr": 0.001, "server_opt_betas": [0.9, 0.99]}

In [8]:
x2  ={"checkpoint": "roberta-base", "ds_path": "glue", "ds_name": "mrpc", "num_labels": 2, "num_clients": 100, "clients_per_round": 10, "alpha": 1.0, "batch_size": 8, "local_epochs": 1, "total_rounds": 1000, "server_opt_name": "Adam", "client_opt_name": "SGD", "server_opt_lr": 0.001, "server_opt_betas": [0.9, 0.99]}

In [10]:
x1

{'checkpoint': 'roberta-base',
 'ds_path': 'glue',
 'ds_name': 'mrpc',
 'num_labels': 2,
 'num_clients': 100,
 'clients_per_round': 10,
 'alpha': 1.0,
 'batch_size': 8,
 'local_epochs': 1,
 'total_rounds': 1000,
 'server_opt_name': 'Adam',
 'client_opt_name': 'SGD',
 'server_opt_lr': 0.001,
 'server_opt_betas': [0.9, 0.99]}

In [11]:
x2

{'checkpoint': 'roberta-base',
 'ds_path': 'glue',
 'ds_name': 'mrpc',
 'num_labels': 2,
 'num_clients': 100,
 'clients_per_round': 10,
 'alpha': 1.0,
 'batch_size': 8,
 'local_epochs': 1,
 'total_rounds': 1000,
 'server_opt_name': 'Adam',
 'client_opt_name': 'SGD',
 'server_opt_lr': 0.001,
 'server_opt_betas': [0.9, 0.99]}

In [12]:
'hp_0.json'.split('.')

['hp_0', 'json']

In [14]:
{**{'mike':1}, **{}}

{'mike': 1}

In [3]:
import numpy as np

In [1]:
round_variance = [0.05, 0.06, 0.08, 1., 1.2]

In [4]:
# number of samplings
n = len(round_variance)

# linear weights: w_i = i (from 1 to n)
weights = np.arange(1, n + 1)

In [5]:
weights

array([1, 2, 3, 4, 5])

In [6]:
weighted_sum = np.dot(weights, round_variance) / np.sum(weights)

In [7]:
weighted_sum

0.6940000000000001

In [1]:
import torch

In [8]:
(torch.dot(torch.rand(10), torch.rand(10))**2).item()

5.834362506866455

In [9]:
sum(torch.rand(10)) / len(torch.rand(10))

tensor(0.4978)

In [21]:
for r in range(10):
    print(r)

0
1
2
3
4
5
6
7
8
9


In [11]:
r

9

In [17]:
len(list(range(9, 10+9)))

10

In [22]:
for r in range(r+1, 10+r+1):
    print(r)

10
11
12
13
14
15
16
17
18
19


In [23]:
5**(0.9)

4.256699612603923

In [26]:
import numpy as np

In [27]:
def compute_custom_weights(p, n):
    """
    Computes the custom weights w_i = (i^p) / sum(i^p) for i from 1 to n.
    
    Parameters:
    - p: Power parameter that controls how sharply weights increase.
    - n: Total number of elements.

    Returns:
    - weights: A numpy array of length n containing the weights.
    """
    indices = np.arange(1, n + 1)
    weights = indices**p
    normalized_weights = weights / np.sum(weights)
    
    return normalized_weights

In [37]:
compute_custom_weights(1/3, 10)

array([0.05894795, 0.07426976, 0.08501766, 0.09357404, 0.10079958,
       0.10711554, 0.11276337, 0.1178959 , 0.12261668, 0.12699951])

In [35]:
compute_custom_weights(0.5, 10)

array([0.04450719, 0.06294268, 0.07708872, 0.08901439, 0.09952111,
       0.10901991, 0.11775496, 0.12588535, 0.13352158, 0.1407441 ])

In [30]:
compute_custom_weights(1, 10)

array([0.01818182, 0.03636364, 0.05454545, 0.07272727, 0.09090909,
       0.10909091, 0.12727273, 0.14545455, 0.16363636, 0.18181818])

In [28]:
compute_custom_weights(2, 10)

array([0.0025974 , 0.01038961, 0.02337662, 0.04155844, 0.06493506,
       0.09350649, 0.12727273, 0.16623377, 0.21038961, 0.25974026])

In [29]:
compute_custom_weights(3, 10)

array([0.00033058, 0.00264463, 0.00892562, 0.02115702, 0.04132231,
       0.07140496, 0.11338843, 0.1692562 , 0.24099174, 0.33057851])